/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LangRouteRouteImport } from './routes/$lang/route'
import { Route as LangIndexRouteImport } from './routes/$lang/index'
import { Route as LangContactsIndexRouteImport } from './routes/$lang/contacts/index'
import { Route as LangKategoriiIndexRouteImport } from './routes/$lang/kategorii/index'
import { Route as LangPagesSlugRouteImport } from './routes/$lang/pages/$slug'
import { Route as LangProductSlugRouteImport } from './routes/$lang/product/$slug'
import { Route as LangProductsIndexRouteImport } from './routes/$lang/products/index'
import { Route as LangProductsSlugRouteImport } from './routes/$lang/products/$slug'
import { Route as LangUsefulMoreSlugRouteImport } from './routes/$lang/useful-more/$slug'
import { Route as LangUsefulIndexRouteImport } from './routes/$lang/useful/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LangRouteRoute = LangRouteRouteImport.update({
  id: '/$lang',
  path: '/$lang',
  getParentRoute: () => rootRouteImport,
} as any)
const LangIndexRoute = LangIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangContactsIndexRoute = LangContactsIndexRouteImport.update({
  id: '/contacts/',
  path: '/contacts/',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangKategoriiIndexRoute = LangKategoriiIndexRouteImport.update({
  id: '/kategorii/',
  path: '/kategorii/',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangPagesSlugRoute = LangPagesSlugRouteImport.update({
  id: '/pages/$slug',
  path: '/pages/$slug',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangProductSlugRoute = LangProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangProductsIndexRoute = LangProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangProductsSlugRoute = LangProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangUsefulMoreSlugRoute = LangUsefulMoreSlugRouteImport.update({
  id: '/useful-more/$slug',
  path: '/useful-more/$slug',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangUsefulIndexRoute = LangUsefulIndexRouteImport.update({
  id: '/useful/',
  path: '/useful/',
  getParentRoute: () => LangRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteRouteWithChildren
  '/$lang/': typeof LangIndexRoute
  '/$lang/pages/$slug': typeof LangPagesSlugRoute
  '/$lang/product/$slug': typeof LangProductSlugRoute
  '/$lang/products/$slug': typeof LangProductsSlugRoute
  '/$lang/useful-more/$slug': typeof LangUsefulMoreSlugRoute
  '/$lang/contacts/': typeof LangContactsIndexRoute
  '/$lang/kategorii/': typeof LangKategoriiIndexRoute
  '/$lang/products/': typeof LangProductsIndexRoute
  '/$lang/useful/': typeof LangUsefulIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$lang': typeof LangIndexRoute
  '/$lang/pages/$slug': typeof LangPagesSlugRoute
  '/$lang/product/$slug': typeof LangProductSlugRoute
  '/$lang/products/$slug': typeof LangProductsSlugRoute
  '/$lang/useful-more/$slug': typeof LangUsefulMoreSlugRoute
  '/$lang/contacts': typeof LangContactsIndexRoute
  '/$lang/kategorii': typeof LangKategoriiIndexRoute
  '/$lang/products': typeof LangProductsIndexRoute
  '/$lang/useful': typeof LangUsefulIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteRouteWithChildren
  '/$lang/': typeof LangIndexRoute
  '/$lang/pages/$slug': typeof LangPagesSlugRoute
  '/$lang/product/$slug': typeof LangProductSlugRoute
  '/$lang/products/$slug': typeof LangProductsSlugRoute
  '/$lang/useful-more/$slug': typeof LangUsefulMoreSlugRoute
  '/$lang/contacts/': typeof LangContactsIndexRoute
  '/$lang/kategorii/': typeof LangKategoriiIndexRoute
  '/$lang/products/': typeof LangProductsIndexRoute
  '/$lang/useful/': typeof LangUsefulIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$lang'
    | '/$lang/'
    | '/$lang/pages/$slug'
    | '/$lang/product/$slug'
    | '/$lang/products/$slug'
    | '/$lang/useful-more/$slug'
    | '/$lang/contacts/'
    | '/$lang/kategorii/'
    | '/$lang/products/'
    | '/$lang/useful/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$lang'
    | '/$lang/pages/$slug'
    | '/$lang/product/$slug'
    | '/$lang/products/$slug'
    | '/$lang/useful-more/$slug'
    | '/$lang/contacts'
    | '/$lang/kategorii'
    | '/$lang/products'
    | '/$lang/useful'
  id:
    | '__root__'
    | '/'
    | '/$lang'
    | '/$lang/'
    | '/$lang/pages/$slug'
    | '/$lang/product/$slug'
    | '/$lang/products/$slug'
    | '/$lang/useful-more/$slug'
    | '/$lang/contacts/'
    | '/$lang/kategorii/'
    | '/$lang/products/'
    | '/$lang/useful/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LangRouteRoute: typeof LangRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang': {
      id: '/$lang'
      path: '/$lang'
      fullPath: '/$lang'
      preLoaderRoute: typeof LangRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/': {
      id: '/$lang/'
      path: '/'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangIndexRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/contacts/': {
      id: '/$lang/contacts/'
      path: '/contacts'
      fullPath: '/$lang/contacts/'
      preLoaderRoute: typeof LangContactsIndexRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/kategorii/': {
      id: '/$lang/kategorii/'
      path: '/kategorii'
      fullPath: '/$lang/kategorii/'
      preLoaderRoute: typeof LangKategoriiIndexRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/pages/$slug': {
      id: '/$lang/pages/$slug'
      path: '/pages/$slug'
      fullPath: '/$lang/pages/$slug'
      preLoaderRoute: typeof LangPagesSlugRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/product/$slug': {
      id: '/$lang/product/$slug'
      path: '/product/$slug'
      fullPath: '/$lang/product/$slug'
      preLoaderRoute: typeof LangProductSlugRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/products/': {
      id: '/$lang/products/'
      path: '/products'
      fullPath: '/$lang/products/'
      preLoaderRoute: typeof LangProductsIndexRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/products/$slug': {
      id: '/$lang/products/$slug'
      path: '/products/$slug'
      fullPath: '/$lang/products/$slug'
      preLoaderRoute: typeof LangProductsSlugRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/useful-more/$slug': {
      id: '/$lang/useful-more/$slug'
      path: '/useful-more/$slug'
      fullPath: '/$lang/useful-more/$slug'
      preLoaderRoute: typeof LangUsefulMoreSlugRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/useful/': {
      id: '/$lang/useful/'
      path: '/useful'
      fullPath: '/$lang/useful/'
      preLoaderRoute: typeof LangUsefulIndexRouteImport
      parentRoute: typeof LangRouteRoute
    }
  }
}

interface LangRouteRouteChildren {
  LangIndexRoute: typeof LangIndexRoute
  LangPagesSlugRoute: typeof LangPagesSlugRoute
  LangProductSlugRoute: typeof LangProductSlugRoute
  LangProductsSlugRoute: typeof LangProductsSlugRoute
  LangUsefulMoreSlugRoute: typeof LangUsefulMoreSlugRoute
  LangContactsIndexRoute: typeof LangContactsIndexRoute
  LangKategoriiIndexRoute: typeof LangKategoriiIndexRoute
  LangProductsIndexRoute: typeof LangProductsIndexRoute
  LangUsefulIndexRoute: typeof LangUsefulIndexRoute
}

const LangRouteRouteChildren: LangRouteRouteChildren = {
  LangIndexRoute: LangIndexRoute,
  LangPagesSlugRoute: LangPagesSlugRoute,
  LangProductSlugRoute: LangProductSlugRoute,
  LangProductsSlugRoute: LangProductsSlugRoute,
  LangUsefulMoreSlugRoute: LangUsefulMoreSlugRoute,
  LangContactsIndexRoute: LangContactsIndexRoute,
  LangKategoriiIndexRoute: LangKategoriiIndexRoute,
  LangProductsIndexRoute: LangProductsIndexRoute,
  LangUsefulIndexRoute: LangUsefulIndexRoute,
}

const LangRouteRouteWithChildren = LangRouteRoute._addFileChildren(
  LangRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LangRouteRoute: LangRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
